# Generated by Django 2.0.4 on 2018-04-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=12)),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('available_date', models.DateField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.State')),
            ],
            options={
                'verbose_name_plural': 'Property Listings',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
