# Generated by Django 2.0.4 on 2018-04-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180409_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
