# Generated by Django 2.0.4 on 2018-04-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_getdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetDate',
        ),
    ]
